CREATE INDEX IF NOT EXISTS orders_user_created_idx ON public.orders (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS orders_status_created_idx ON public.orders (status, created_at DESC);
CREATE INDEX IF NOT EXISTS order_items_order_idx ON public.order_items (order_id);
CREATE INDEX IF NOT EXISTS order_items_seller_idx ON public.order_items (seller_id);
CREATE INDEX IF NOT EXISTS order_items_product_idx ON public.order_items (product_id);
CREATE INDEX IF NOT EXISTS delivery_updates_order_created_idx ON public.delivery_updates (order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS wallet_tx_seller_created_idx ON public.wallet_transactions (seller_id, created_at DESC);
CREATE INDEX IF NOT EXISTS wallet_tx_order_idx ON public.wallet_transactions (order_id);
CREATE INDEX IF NOT EXISTS withdrawals_seller_status_idx ON public.withdrawal_requests (seller_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS reviews_product_approved_idx ON public.reviews (product_id, approved, created_at DESC);
CREATE INDEX IF NOT EXISTS reviews_user_idx ON public.reviews (user_id);
CREATE INDEX IF NOT EXISTS reviews_order_idx ON public.reviews (order_id);
CREATE INDEX IF NOT EXISTS products_seller_idx ON public.products (seller_id);
CREATE INDEX IF NOT EXISTS products_created_idx ON public.products (created_at DESC);
CREATE INDEX IF NOT EXISTS sellers_owner_idx ON public.sellers (owner_id);
CREATE INDEX IF NOT EXISTS user_roles_user_idx ON public.user_roles (user_id);
ANALYZE public.orders;
ANALYZE public.order_items;
ANALYZE public.products;
ANALYZE public.sellers;